<?php

namespace App\RestauranteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasaRepository extends EntityRepository
{
}
